#!/bin/bash
#
# @file   far
# @author David Weber david.weber.dfw@gmail.com
# @date   10/06/2024
#
# @brief far module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 3 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: $BASENAME <files_to_find> <search_string> <replacement_string>"
  exit -1
else
  FILES_TO_FIND="$1"
  SEARCH_STRING="$2"
  REPLACEMENT_STRING="$3"
fi
find . -name ${FILES_TO_FIND} -exec sed -i "s/$SEARCH_STRING/$REPLACEMENT_STRING/g" {} +
