#!/bin/bash

if [ $# -ne 3 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: $BASENAME <files_to_find> <search_string> <replacement_string>"
  exit -1
else
  FILES_TO_FIND="$1"
  SEARCH_STRING="$2"
  REPLACEMENT_STRING="$3"
fi
find ./ -name "${FILES_TO_FIND}" -exec sed -i "s/$SEARCH_STRING/$REPLACEMENT_STRING/g" {} +
