#!/bin/bash
#
# @file   fcp
# @author David Weber david.weber.dfw@gmail.com
# @date   10/08/2024
#
# @brief fcp module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 2 ]; then
  SCRIPT_NAME=`basename ${0}`
  echo "Usage: ${SCRIPT_NAME} <files> <destination_directory>"
  exit -1
fi

FILES=${1}
DESTINATION_DIR=${2}

if [ ! -d "${2}" ]; then
  read -p "${DESTINATION_DIR} does not exist - Create? (Y/N) " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit -2
  echo "Creating directory: ${DESTINATION_DIR}"
  mkdir -p ${DESTINATION_DIR}
fi

find . -name ${FILES} -exec cp {} ${DESTINATION_DIR} \;
