#!/bin/bash
#
# @file   ff
# @author David Weber david.weber.dfw@gmail.com
# @date   10/06/2024
#
# @brief ff module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [[ ${2} == "" ]]
then
 find ./ -name "${1}"
else
 find ${2} -name "${1}"
fi

