#!/bin/bash
#
# @file   mk_bootable_flash_disk
# @author David Weber david.weber.dfw@gmail.com
# @date   11/17/2024
#
# @brief mk_bootable_flash_disk module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#if [ "${EUID}" -ne 0 ]
#  then echo "root privilege required to run this script"
#  exit -1
#fi

if [ $# -ne 2 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: ${BASENAME} <disk> <iso file>"
  exit -2
fi

DISK=${1}
ISO_FILE=${2}

if [ ! -e "${DISK}" ]; then
  echo "${DISK} not found"
  exit -3
fi

if [ ! -f "${ISO_FILE}" ]; then
  echo "${ISO_FILE} not found"
  exit -4
fi

read -p "Overwrite ${DISK} with ${ISO_FILE} (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit -2
sudo dd if=${ISO_FILE} of=${DISK} bs=2M status=progress
