#!/bin/bash
#
# @file   mk_branch
# @author David Weber david.weber.dfw@gmail.com
# @date   09/28/2024
#
# @brief mk_branch module implementation
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 1 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: ${BASENAME} <new branch name>"
  exit -1
fi

NEW_BRANCH=${1}

git checkout -b ${NEW_BRANCH}
read -p "Push new branch ${NEW_BRANCH} to remote repo? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit -2
git push -u origin ${NEW_BRANCH}

