#!/bin/bash
#
# @file   replace
# @author David Weber david.weber.dfw@gmail.com
# @date   07/31/2024
#
# @brief replace strings in specified files
#
# Copyright (C) 2024 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

if [ $# -ne 4 ]; then
  echo "Usage: $0 <string_to_replace> <replacement_string> <file(s)/wildcard>"
  exit -1
fi

STRING_TO_REPLACE=${1}
REPLACEMENT_STRING=${2}
FILES=${3}

find . -name "$FILES" -exec sed -i 's/'"$STRING_TO_REPLACE"'/'"$REPLACEMENT_STRING"'/g' {} \;
