#!/bin/bash
#
# @file   uz
# @author David Weber david.weber.dfw@gmail.com
# @date   05/06/2025
#
# @brief uz (unzip) module implementation
#
# Copyright (C) 2025 David Weber
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ $# -ne 1 ]; then
  BASENAME=`basename ${0}`
  echo "Usage: ${BASENAME} <zip filename>"
  exit -1
fi

ZIP_OUTPUT_DIR=`basename ${1}`

read -p "Create outputdir ${ZIP_OUTPUT_DIR}? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit -2

/usr/bin/unzip -d ${ZIP_OUTPUT_DIR}
